### ISSUE TITLE
Evaluation and best move differ in 2 GUIs

### ISSUE THREAD

**Issue by tissatussa** [amanjpro/zahak#192]
While testing the new Zahak v8.0 dev (by git clone & compile) i discovered a strange thing : it's evaluation and 'best move' differ when running in SCID and CuteChess.

I tested the following position : 8/p5pp/1pk1n3/5p2/P1n5/2NN2KP/5PP1/8 w - - 0 28

![zahak_8 0-dev_in_scid](https://user-images.githubusercontent.com/1109281/142780281-d2fc8e03-b4ed-42c7-b1cf-4fdaf5361359.png)

White to move. Here you see the output in SCID. For a long time Zahak considered Nb4+ best move. At a few depths it changed its mind to Nf4 or Kh4, but after all it decided Nb4+ was best. In SCID i let it run endlessly, and for my test i stopped the engine at depth 23 after 81 seconds. I used CuteChess for engine-vs-engine play (setting 120 sec per player for the whole game + 1 sec bonus) and here Zahak played h4 after 5.8 seconds, reaching depth 9 :

![zahak_8 0-dev_in_cutechess](https://user-images.githubusercontent.com/1109281/142780288-04d489d7-1f48-4574-9b8a-37377c91af1d.png)

```
[Event "engine-vs-engine"]
[Site "?"]
[Date "2021.11.21"]
[White "Zahak v8.0 dev NNUE"]
[Black "TuxedoCat v0.0.2"]
[Result "1-0"]
[FEN "8/p5pp/1pk5/5p2/P1nn4/2NN3P/5PPK/8 w - - 0 27"]
[GameDuration "00:01:54"]
[PlyCount "43"]
[SetUp "1"]
[TimeControl "120+1"]

1. Kg3 {-2.02/9 8.2s} Ne6 {+1.00/4 0.22s} 2. h4 {-1.95/9 5.8s} Nc5 {+1.00/4 0.30s} 3. Nb4+ {-1.92/9 12s} Kb7 {+2.11/5 0.94s} 4. Kf4 {-1.77/10 7.9s} g6 {+1.00/4 0.26s} 5. Kg5 {-1.12/10 7.8s} a5 {+1.00/4 0.26s} 6. Nbd5 {-1.14/10 3.9s} Ne4+ {+0.05/4 0.26s} 7. Kh6 {+0.56/10 4.9s} Nxc3 {0.00/4 0.23s} 8. Nxc3 {+1.89/13 6.4s} Nb2 {+0.03/5 0.79s} 9. Kxh7 {+4.91/12 3.0s} f4 {-0.13/5 0.67s} 10. Kxg6 {+5.07/12 2.8s} Nd3 {-1.08/5 0.60s} 11. h5 {+6.54/12 5.4s} Nxf2 {-0.40/5 0.82s} 12. h6 {+13.33/12 3.2s} Nd3 {-0.40/5 0.85s} 13. h7 {+14.16/12 3.2s} Ne5+ {-3.45/5 1.1s} 14. Kf6 {+21.08/11 9.0s} f3 {-6.60/5 1.3s} 15. gxf3 {+22.55/11 2.2s} Nd7+ {-7.86/5 0.69s} 16. Kf5 {+22.46/12 2.7s} Nc5 {-9.08/5 0.52s} 17. h8=Q {+35.50/11 3.8s} Nd3 {-9.08/5 1.2s} 18. Nb5 {+M11/12 5.7s} Nb4 {-9.08/5 0.85s} 19. Qd8 {+M7/25 1.8s} Na6 {-9.08/5 0.72s} 20. Ke5 Nc5 {-12.08/4 0.31s} 21. Qc7+ {+M3/100 0.022s} Ka6 {-12.08/2 1.2s} 22. Qa7# {+M1/100 0.025s, White mates} 1-0
```

Note the starting position was 1 move earlier, but to consult SCID i entered the position that followed after 1 move. 

The CuteChess screenshot shows that Zahak considered Nb4+ best move after 3 sec at depth 8, and h4 after 25 sec at depth 9, but to reproduce its behaviour and create the screenshot, i again let it run in CuteChess with much longer thinking time .. obviously it played h4 after 5.9 sec, not Nb4+. However, SCID shows h4 was never considered !? Also the evaluation in SCID (-2.07 after 4.31 sec at depth 17) differs from CuteChess (-1.95 after 5.8 sec at depth 9).

I have no clue how to explain this .. did i do a proper test? It seems Zahak (and maybe any engine) is running much faster in SCID and the evaluation differs a lot.

I'm on Xubuntu 20.04 64-bit. Both my GUIs are newest versions, i use same settings in both, eg. 64 Mb hash and MPV 1 and 1 thread.

**Comment by amanjpro** [comment]
> Note the starting position was 1 move earlier, but to consult SCID i entered the position that followed after 1 move.

This is the reason, chess engines gather lots of information while playing, namely in Hash and history, and these greatly affect the chosen moves

**Comment by amanjpro** [comment]
Zahak doesn't talk to any GUI, except by a lanauge called UCI, the GUI has no effect on the outcome of a search

**Comment by amanjpro** [comment]
Here is what I have and I believe it matches what is in Scid:

```
go
info depth 1 seldepth 2 hashfull 0 tbhits 0 nodes 55 nps 137338 score cp -225 time 0 pv c3b5
info depth 2 seldepth 6 hashfull 0 tbhits 0 nodes 442 nps 298098 score cp -220 time 1 pv d3b4 c6d6 c3b5 d6c5
info depth 3 seldepth 9 hashfull 0 tbhits 0 nodes 2756 nps 702713 score cp -180 time 3 pv d3b4 c6d7 c3b5 a7a5
info depth 4 seldepth 8 hashfull 0 tbhits 0 nodes 3425 nps 704229 score cp -198 time 4 pv c3b5 a7a6 d3b4 c6b7 b5c3
info depth 5 seldepth 9 hashfull 0 tbhits 0 nodes 4189 nps 661587 score cp -208 time 6 pv c3b5 a7a6 d3b4 c6b7 b5c3 c4e5
info depth 6 seldepth 9 hashfull 0 tbhits 0 nodes 4602 nps 661057 score cp -204 time 6 pv c3b5 a7a6 d3b4 c6b7 b5c3 c4e5 f2f3
info depth 7 seldepth 10 hashfull 1 tbhits 0 nodes 5994 nps 686189 score cp -188 time 8 pv d3b4 c6d7 h3h4 c4b2 c3b5 a7a5
info depth 8 seldepth 19 hashfull 1 tbhits 0 nodes 17553 nps 630004 score cp -206 time 27 pv d3b4 c6c5 b4a6 c5d6 c3b5 d6c6 a6b4 c6b7 b5c3 a7a5 b4d3
info depth 9 seldepth 20 hashfull 1 tbhits 0 nodes 25358 nps 645248 score cp -201 time 39 pv d3b4 c6c5 b4a6 c5d6 c3b5 d6c6 a6b4 c6b7 b4d3 a7a6 b5c3 c4d2
info depth 10 seldepth 19 hashfull 2 tbhits 0 nodes 31039 nps 649008 score cp -197 time 47 pv d3b4 c6c5 b4a6 c5d6 c3b5 d6c6 a6b4 c6b7 b4d3 a7a6 b5c3 c4d2 f2f3
info depth 11 seldepth 20 hashfull 2 tbhits 0 nodes 51815 nps 647369 score cp -191 time 80 pv d3b4 c6c5 b4a6 c5d6 c3b5 d6c6 a6b4 c6b7 h3h4 g7g6 b5c3 a7a5 b4d3 c4d6 g3f3 b7c6 f3e3
info depth 12 seldepth 27 hashfull 6 tbhits 0 nodes 172757 nps 715431 score cp -206 time 241 pv d3b4 c6d7 c3b5 a7a5 b4d3 d7c6 h3h4 g7g6 h4h5 g6h5 g3h4 e6c5 d3c5 c6c5
info depth 13 seldepth 25 hashfull 13 tbhits 0 nodes 352720 nps 792550 score cp -212 time 445 pv d3b4 c6d7 b4a6 c4e5 c3b5 e5c6 h3h4 g7g6 g3f3 d7e7 f3g3 e7f6 a6c7 e6c7 b5c7
info depth 14 seldepth 23 hashfull 13 tbhits 0 nodes 439167 nps 816212 score cp -216 time 538 pv d3b4 c6d7 b4d3 a7a6 d3b4 a6a5 b4d3 d7d6 g3h4 d6c6 f2f4 c6d6 c3b5 d6d5 h4h5 d5e4
info depth 15 seldepth 25 hashfull 15 tbhits 0 nodes 552893 nps 841321 score cp -207 time 657 pv d3b4 c6d7 b4d3 a7a6 d3f4 d7d6 h3h4 c4b2 g3f3 d6e5 f4e6 e5e6 a4a5 b6a5 f3e3
info depth 16 seldepth 27 hashfull 31 tbhits 0 nodes 971382 nps 901182 score cp -195 time 1077 pv d3b4 c6d7 b4d3 a7a6 d3f4 h7h6 h3h4 g7g5 h4g5 h6g5 f4e6 d7e6 f2f4 g5g4 g3h4 c4e3
info depth 17 seldepth 24 hashfull 33 tbhits 0 nodes 1089914 nps 910740 score cp -206 time 1196 pv d3b4 c6d7 b4d3 a7a6 d3f4 d7d6 f4e6 d6e6 g3f4 c4e5 f4e3 h7h6 e3d4 e5c6 d4e3 g7g5 f2f4 e6d6 f4g5 h6g5
info depth 18 seldepth 29 hashfull 48 tbhits 0 nodes 1575662 nps 937601 score cp -203 time 1680 pv d3b4 c6d7 b4d3 a7a6 d3f4 d7d6 f4e6 d6e6 g3f4 c4e5 f4e3 h7h6 f2f3 e5c6 f3f4 e6d6 g2g4 f5g4 h3g4 d6c5
quiinfo depth 19 seldepth 30 hashfull 66 tbhits 0 nodes 2226247 nps 960457 score cp -208 time 2317 pv d3b4 c6c7 c3b5 c7b7 b4d3 a7a5 h3h4 b7c6 h4h5 c4d6 b5d6 c6d6 f2f3 e6c5 d3b2 g7g5 h5g6 h7g6 b2c4 d6c6 c4e5 c6d5 e5g6 c5a4
```

**Comment by amanjpro** [comment]
I believe this is a no issue, I'll close it. If you feel I haven't answered your question yet, feel free to reopen it
